version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pass
    depends_on:
      - db

  backend-app:
    image: ghcr.io/goabhay/todo:1.7
    ports:
      - "8083:8081"
    depends_on:
      - db
      - phpmyadmin
volumes:
  mysql-store:
    driver: local